[package]
name = "bevy-robbo"
version = "0.1.0"
authors = ["Mariusz Kryński <mrk@sed.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {path="../bevy/", features=["vorbis"]}
rand = "0.7"
anyhow = "1.0"
uuid = "0.8"
structopt = "0.3"

[profile.dev]
opt-level = 1